### PR TITLE
Add ResizeContent feature to Window

### LINKED ISSUE #343: Electron `window.setContentSize` equivalent?
Currently, even with `UseContentSize` option set to true in `WindowOptions`, calling `window.Resize()` still resizes the browser window instead of the page viewport.

Is there an equivalent method of calling `window.setContentSize` like this [in the Electron document](https://github.com/electron/electron/blob/main/docs/api/browser-window.md#winsetcontentsizewidth-height-animate)?

Thanks.

### PR DESCRIPTION
**Pull request by maddie**
Fixes #343

### CODE REVIEW

**Review by asticode — APPROVED** [review]
👍 

I'll merge once `astilectron` new tag is created.

**Comment by asticode** [comment]
fyi I've created a `v0.26.0` tag

**Comment by maddie** [comment]
Hmm, the `v0.26.0` tag seems to be tagged on the previous commit.

**Comment by asticode** [comment]
you're right, my bad 😱 

I've created a `v0.27.0` tag that should be good this time

**Pull request merged**
