### PR TITLE
Remove option for context isolation

### PR DESCRIPTION
**Pull request by paolobelluticm**
Removes the option to set `ContextIsolation` from `WindowOptions.WebPreferences`. The property is now hardcoded to false in astilectron (see https://github.com/asticode/astilectron/pull/45).

[Context isolation](https://www.electronjs.org/docs/tutorial/context-isolation) appears to be incompatible with astilectron, but it's enabled by default by Electron starting with major version 12.
Issue: https://github.com/asticode/go-astilectron/issues/318

### CODE REVIEW

**Comment by paolobelluticm** [comment]
CI tests fail, but I think the problem lies elsewhere (something about strings containing an extra `path: ""`, not something I'm touching here).

**Comment by asticode** [comment]
> CI tests fail, but I think the problem lies elsewhere (something about strings containing an extra `path: ""`, not something I'm touching here).

Yeah you're right, just fixed it

**Comment by asticode** [comment]
Could you updated `astilectron` version to `v0.48.0` [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L16) as well?

**Comment by paolobelluticm** [comment]
Done.

**Comment by asticode** [comment]
FYI I've created new tags for the whole ecosystem

Cheers

**Pull request merged**
